### ISSUE TITLE
Injecting begin/end hook points at http level

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Node.Prototype#1]
Currently we are hooking in at the express level to see the begin/end of a request, longer term well will probably want to go lower down and tap in at the http level and wrap the `createServer` call. Here is some basic info around how the layers are built on top of each other.

**Comment by avanderhoorn** [comment]
Note this is non urgent, just capturing the thought process.

**Comment by mike-kaufman** [comment]
@avanderhoorn - thanks for the comment.  Did you forget to add a hyperlink?  I'm not clear what you're referring to with "here is some basic info around how the layers are built on top of each other".

**Comment by philliphoff** [comment]
Done with #11.
