### ISSUE TITLE
Use Continuation Local Storage for storing Context data

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Node.Prototype#2]
In .net we have the following which we use for ambient passing around [context data](https://github.com/Glimpse/Glimpse.Prototype/blob/dev/src/Glimpse.Common/Common/ContextData.cs). This stores the data on the thread which means that we don't need to worry about manually passing it around. In Node, the equivalent is [Continuation Local Storage](https://github.com/othiym23/node-continuation-local-storage). It's been a little while since I looked into it, but it should do what we need.

**Comment by mike-kaufman** [comment]
This is done with my latest check-in.  There's a glimpseSession.js file, with a set of exports for initializing & looking up data in CLS.  Please let me know if you have feedback.
