### ISSUE TITLE
Add a git commit hook to validate linting

### ISSUE THREAD

**Issue by jasonyueyang** [Glimpse/Glimpse.Node.Prototype#37]

**Comment by jasonyueyang** [comment]
I can use ghooks (https://www.npmjs.com/package/ghooks) to set up a pre-commit validation step for linting. This works really well both from the command line environment and VS Code.

The implication is that `glup lint` needs to pass before `git commit` can go through. 

Is this helpful? If so, I'll submit a PR.

**Comment by avanderhoorn** [comment]
Do you know if you can set these up at a repo level - meaning if its something that we each need to setup manually or people just get it when they try and commit any time after cloning.

**Comment by jasonyueyang** [comment]
No manual setup required. Folks cloning our repo will get this automatically.

**Comment by avanderhoorn** [comment]
Lets do it then! Question is whether we want to force tests as well...

**Comment by philliphoff** [comment]
As discussed in person, adding such a hook does have the disadvantage of not allowing one to backup one's changes to a remote branch without first fixing it up.  If we are going to have a hook, then it should come with a means to override it when necessary (e.g. for personal or prototype branches, pri-0 build break fixes, etc.).  Or perhaps only require it for the master branch (but then, it's likely not that useful given our feature-branch-then-PR-into-master process).

That said, I'm rather less concerned with linting errors sneaking their way into the codebase than I am broken unit tests or actual build failures.  If we have such a hook, it seems like we ought to make the most of it by requiring a full build, lint, and test pass.

My question would be, does this type of hook give us a significant benefit beyond a CI system that validates a clean build of a feature branch during a PR (such as Travis CI should give us)?

**Comment by avanderhoorn** [comment]
I agree about the CI vs doing it as a hook, that said it can be a good prompt. Re the hook preventing you from committing, you can always still commit via `git commit --no-verify`. The fact that this exists means the CI will have to do at least what the hook does and that if we choose to have it the hook acts as a reminder. My main concern with whether it will become annoying (I've never really used a repo that has used hooks before) but if it does we can always remove it.

**Comment by jasonyueyang** [comment]
If we want to bypass the validation, `git commit --no-verify` works well. 

I suggest we try the git hook for a while. If it becomes too heavy-weight, we can tweak it later.
