### ISSUE TITLE
Remove .vscode

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Node.Prototype#6]
Does `.vscode` need to be checked in?

**Comment by mike-kaufman** [comment]
This contains debug launch configuration info, so it should be checked in.  For example, see the tslint extension for VSCode here:  https://github.com/Microsoft/vscode-tslint/.  They check in the .vscode folder also.

**Comment by avanderhoorn** [comment]
Great, just wanted to check
